# Generated by Django 5.0.4 on 2024-12-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nt1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(default='enter title'),
        ),
    ]
